// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0ZyHu9Tu1V_6WbCeaN8jPNf4M0QBQfOk',
    appId: '1:77765068895:web:dc0b57b7bf2563c4ca73ea',
    messagingSenderId: '77765068895',
    projectId: 'shelfit-f6a31',
    authDomain: 'shelfit-f6a31.firebaseapp.com',
    storageBucket: 'shelfit-f6a31.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxDvexkR0T95KywTOX5YNG5kbqCokMwU0',
    appId: '1:77765068895:android:4248fce8b6b3a274ca73ea',
    messagingSenderId: '77765068895',
    projectId: 'shelfit-f6a31',
    storageBucket: 'shelfit-f6a31.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfB5v5y8JuxrKSqRCgidJ2TA7a0eAmB5w',
    appId: '1:77765068895:ios:83e9b4dab3436962ca73ea',
    messagingSenderId: '77765068895',
    projectId: 'shelfit-f6a31',
    storageBucket: 'shelfit-f6a31.firebasestorage.app',
    iosBundleId: 'com.example.shelfit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfB5v5y8JuxrKSqRCgidJ2TA7a0eAmB5w',
    appId: '1:77765068895:ios:83e9b4dab3436962ca73ea',
    messagingSenderId: '77765068895',
    projectId: 'shelfit-f6a31',
    storageBucket: 'shelfit-f6a31.firebasestorage.app',
    iosBundleId: 'com.example.shelfit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC0ZyHu9Tu1V_6WbCeaN8jPNf4M0QBQfOk',
    appId: '1:77765068895:web:eb9a32d7355bea93ca73ea',
    messagingSenderId: '77765068895',
    projectId: 'shelfit-f6a31',
    authDomain: 'shelfit-f6a31.firebaseapp.com',
    storageBucket: 'shelfit-f6a31.firebasestorage.app',
  );

}